apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sentryflow.namespace | default "sentryflow" }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.sentry.namespaceLabel | default "sentryflow" }}
